Global:
  Name: "DiscordBot"
  Prefix: "d!"
  Version: "1.0"
  Client: "41646848646413854853"

Initialization:
  Activity: "{{Global.Prefix}}help"
  Status: 'dnd' #invisible / online / idle / dnd

Paths:
  Commands: "./commands/"