Global:
  Name: "DiscordBot"
  Prefix: "d!"
  Version: "1.0"
  Client: "e.g. Your Bot's client id (client.user.id)"

Initialization:
  Activity: "{{Global.Prefix}}help"
  Status: 'dnd' #invisible / online / idle / dnd

Paths:
  Commands: "./commands/"
